aliases:
  - &restore-cache
    key: dependencies-{{ checksum "build.gradle.kts" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
  - &save-cache
    key: dependencies-{{ checksum "build.gradle.kts" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
    paths:
      - ~/.gradle

version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/auto-truth
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache: *restore-cache
      - run:
          name: Build 'annotations' module
          command: ./gradlew :annotations:build --stacktrace
          no_output_timeout: 3m
      - run:
          name: Build 'processor' module
          command: ./gradlew :processor:build --stacktrace
          no_output_timeout: 3m
      - save_cache: *save-cache

  test:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/auto-truth
    steps:
      - checkout
      - restore_cache: *restore-cache
      - run:
          name: Test 'processor' module
          command: ./gradlew :processor:test --stacktrace
          no_output_timeout: 3m
      - save_cache: *save-cache
      - store_test_results:
          path: ./processor/test-results/test
      - store_artifacts:
          path: ./processor/reports/test
          destination: spek

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
